name: "Publish package to GitHub Packages"
on:
  # manual trigger
  workflow_dispatch:
  # release:
  #   types: [created]
  # # runnnig on push to main and develop branches
  # push:
  #   branches:
  #     - main
  #     - develop
  #     - jfrog_test
  # # running on pull requests to main and develop branches
  # pull_request:
  #   branches:
  #     - main
  #     - develop

jobs:
  build_and_publish_packages:
    # build job will run on ubuntu-latest github-hosted runner
    runs-on: ubuntu-latest
    # defining permissions for the job - read contents, write packages, write id-token. Link to the documentation - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idpermissions
    # security-events permission is required for CodeQL analysis
    # enforcing policy for the job - only users with write access to the repository can trigger the job. Link to the documentation - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenforce_admins
    permissions:
      actions: read
      contents: read
      packages: write
      id-token: write
      security-events: write
    
    # defining steps for the job as explained above 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # cache maven packages step - caching maven packages to speed up the build process. Link to the documentation - https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
      
      - uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3 # defining cache key and restore keys for the cache step. Link to the documentation - https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
        with:
          path: /root/.m2 # path to the directory where maven packages are stored - /root/.m2 in the container
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Build with Maven
        run: mvn -B package
      
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}